# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chase_main_screen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 200)
        MainWindow.setMinimumSize(QtCore.QSize(700, 200))
        MainWindow.setMaximumSize(QtCore.QSize(700, 200))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Team_Name_label = QtGui.QLabel(self.centralwidget)
        self.Team_Name_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Team_Name_label.setFont(font)
        self.Team_Name_label.setObjectName(_fromUtf8("Team_Name_label"))
        self.Vehicle_Label = QtGui.QLabel(self.centralwidget)
        self.Vehicle_Label.setGeometry(QtCore.QRect(450, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Vehicle_Label.setFont(font)
        self.Vehicle_Label.setObjectName(_fromUtf8("Vehicle_Label"))
        self.dist_label = QtGui.QLabel(self.centralwidget)
        self.dist_label.setGeometry(QtCore.QRect(10, 50, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dist_label.setFont(font)
        self.dist_label.setObjectName(_fromUtf8("dist_label"))
        self.direct_label = QtGui.QLabel(self.centralwidget)
        self.direct_label.setGeometry(QtCore.QRect(310, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.direct_label.setFont(font)
        self.direct_label.setObjectName(_fromUtf8("direct_label"))
        self.Move = QtGui.QPushButton(self.centralwidget)
        self.Move.setGeometry(QtCore.QRect(600, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Move.setFont(font)
        self.Move.setObjectName(_fromUtf8("Move"))
        self.Team_Name_Display = QtGui.QLineEdit(self.centralwidget)
        self.Team_Name_Display.setGeometry(QtCore.QRect(100, 10, 131, 20))
        self.Team_Name_Display.setReadOnly(True)
        self.Team_Name_Display.setPlaceholderText(_fromUtf8(""))
        self.Team_Name_Display.setObjectName(_fromUtf8("Team_Name_Display"))
        self.Car_Type_Display = QtGui.QLineEdit(self.centralwidget)
        self.Car_Type_Display.setGeometry(QtCore.QRect(550, 10, 131, 20))
        self.Car_Type_Display.setReadOnly(True)
        self.Car_Type_Display.setPlaceholderText(_fromUtf8(""))
        self.Car_Type_Display.setObjectName(_fromUtf8("Car_Type_Display"))
        self.dist = QtGui.QDoubleSpinBox(self.centralwidget)
        self.dist.setGeometry(QtCore.QRect(20, 85, 62, 22))
        self.dist.setMaximum(10.0)
        self.dist.setSingleStep(0.1)
        self.dist.setProperty("value", 1.0)
        self.dist.setObjectName(_fromUtf8("dist"))
        self.N = QtGui.QPushButton(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(328, 22, 34, 20))
        self.N.setObjectName(_fromUtf8("N"))
        self.NNE = QtGui.QPushButton(self.centralwidget)
        self.NNE.setGeometry(QtCore.QRect(361, 32, 34, 20))
        self.NNE.setObjectName(_fromUtf8("NNE"))
        self.NE = QtGui.QPushButton(self.centralwidget)
        self.NE.setGeometry(QtCore.QRect(394, 42, 34, 20))
        self.NE.setObjectName(_fromUtf8("NE"))
        self.ENE = QtGui.QPushButton(self.centralwidget)
        self.ENE.setGeometry(QtCore.QRect(408, 61, 35, 20))
        self.ENE.setObjectName(_fromUtf8("ENE"))
        self.E = QtGui.QPushButton(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(423, 80, 35, 20))
        self.E.setObjectName(_fromUtf8("E"))
        self.ESE = QtGui.QPushButton(self.centralwidget)
        self.ESE.setGeometry(QtCore.QRect(408, 99, 35, 20))
        self.ESE.setObjectName(_fromUtf8("ESE"))
        self.SE = QtGui.QPushButton(self.centralwidget)
        self.SE.setGeometry(QtCore.QRect(394, 118, 34, 20))
        self.SE.setObjectName(_fromUtf8("SE"))
        self.SSE = QtGui.QPushButton(self.centralwidget)
        self.SSE.setGeometry(QtCore.QRect(361, 128, 34, 20))
        self.SSE.setObjectName(_fromUtf8("SSE"))
        self.S = QtGui.QPushButton(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(328, 138, 34, 20))
        self.S.setObjectName(_fromUtf8("S"))
        self.NNW = QtGui.QPushButton(self.centralwidget)
        self.NNW.setGeometry(QtCore.QRect(295, 32, 34, 20))
        self.NNW.setObjectName(_fromUtf8("NNW"))
        self.NW = QtGui.QPushButton(self.centralwidget)
        self.NW.setGeometry(QtCore.QRect(262, 42, 34, 20))
        self.NW.setObjectName(_fromUtf8("NW"))
        self.WNW = QtGui.QPushButton(self.centralwidget)
        self.WNW.setGeometry(QtCore.QRect(248, 61, 35, 20))
        self.WNW.setObjectName(_fromUtf8("WNW"))
        self.W = QtGui.QPushButton(self.centralwidget)
        self.W.setGeometry(QtCore.QRect(233, 80, 35, 20))
        self.W.setObjectName(_fromUtf8("W"))
        self.SSW = QtGui.QPushButton(self.centralwidget)
        self.SSW.setGeometry(QtCore.QRect(295, 128, 34, 20))
        self.SSW.setObjectName(_fromUtf8("SSW"))
        self.SW = QtGui.QPushButton(self.centralwidget)
        self.SW.setGeometry(QtCore.QRect(262, 118, 34, 20))
        self.SW.setObjectName(_fromUtf8("SW"))
        self.WSW = QtGui.QPushButton(self.centralwidget)
        self.WSW.setGeometry(QtCore.QRect(248, 99, 35, 20))
        self.WSW.setObjectName(_fromUtf8("WSW"))
        self.refuel = QtGui.QCheckBox(self.centralwidget)
        self.refuel.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.refuel.setFont(font)
        self.refuel.setObjectName(_fromUtf8("refuel"))
        self.status_message = QtGui.QLineEdit(self.centralwidget)
        self.status_message.setGeometry(QtCore.QRect(20, 170, 561, 20))
        self.status_message.setAlignment(QtCore.Qt.AlignCenter)
        self.status_message.setReadOnly(True)
        self.status_message.setObjectName(_fromUtf8("status_message"))
        self.speed = QtGui.QLineEdit(self.centralwidget)
        self.speed.setGeometry(QtCore.QRect(580, 60, 61, 20))
        self.speed.setReadOnly(True)
        self.speed.setObjectName(_fromUtf8("speed"))
        self.speed_label = QtGui.QLabel(self.centralwidget)
        self.speed_label.setGeometry(QtCore.QRect(540, 60, 41, 16))
        self.speed_label.setObjectName(_fromUtf8("speed_label"))
        self.heading_label = QtGui.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(530, 90, 41, 20))
        self.heading_label.setObjectName(_fromUtf8("heading_label"))
        self.direct = QtGui.QLineEdit(self.centralwidget)
        self.direct.setGeometry(QtCore.QRect(580, 90, 61, 20))
        self.direct.setReadOnly(True)
        self.direct.setObjectName(_fromUtf8("direct"))
        self.fuel_level_label = QtGui.QLabel(self.centralwidget)
        self.fuel_level_label.setGeometry(QtCore.QRect(498, 120, 81, 20))
        self.fuel_level_label.setObjectName(_fromUtf8("fuel_level_label"))
        self.fuel_level = QtGui.QLineEdit(self.centralwidget)
        self.fuel_level.setGeometry(QtCore.QRect(580, 120, 61, 20))
        self.fuel_level.setReadOnly(True)
        self.fuel_level.setObjectName(_fromUtf8("fuel_level"))
        self.dist_units = QtGui.QLabel(self.centralwidget)
        self.dist_units.setGeometry(QtCore.QRect(90, 90, 41, 16))
        self.dist_units.setObjectName(_fromUtf8("dist_units"))
        self.speed_unit = QtGui.QLabel(self.centralwidget)
        self.speed_unit.setGeometry(QtCore.QRect(650, 60, 41, 16))
        self.speed_unit.setObjectName(_fromUtf8("speed_unit"))
        self.fuel_level_units = QtGui.QLabel(self.centralwidget)
        self.fuel_level_units.setGeometry(QtCore.QRect(650, 120, 41, 16))
        self.fuel_level_units.setObjectName(_fromUtf8("fuel_level_units"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ISU AMS Storm Chase Simulation", None))
        self.Team_Name_label.setText(_translate("MainWindow", "Team name:", None))
        self.Vehicle_Label.setText(_translate("MainWindow", "Vehicle Type:", None))
        self.dist_label.setText(_translate("MainWindow", "How far do you want to go?", None))
        self.direct_label.setText(_translate("MainWindow", "Direction:", None))
        self.Move.setText(_translate("MainWindow", "Move", None))
        self.N.setText(_translate("MainWindow", "N", None))
        self.NNE.setText(_translate("MainWindow", "NNE", None))
        self.NE.setText(_translate("MainWindow", "NE", None))
        self.ENE.setText(_translate("MainWindow", "ENE", None))
        self.E.setText(_translate("MainWindow", "E", None))
        self.ESE.setText(_translate("MainWindow", "ESE", None))
        self.SE.setText(_translate("MainWindow", "SE", None))
        self.SSE.setText(_translate("MainWindow", "SSE", None))
        self.S.setText(_translate("MainWindow", "S", None))
        self.NNW.setText(_translate("MainWindow", "NNW", None))
        self.NW.setText(_translate("MainWindow", "NW", None))
        self.WNW.setText(_translate("MainWindow", "WNW", None))
        self.W.setText(_translate("MainWindow", "W", None))
        self.SSW.setText(_translate("MainWindow", "SSW", None))
        self.SW.setText(_translate("MainWindow", "SW", None))
        self.WSW.setText(_translate("MainWindow", "WSW", None))
        self.refuel.setText(_translate("MainWindow", "Refuel now?", None))
        self.speed_label.setText(_translate("MainWindow", "Speed:", None))
        self.heading_label.setText(_translate("MainWindow", "Heading:", None))
        self.fuel_level_label.setText(_translate("MainWindow", "Fuel Remaining:", None))
        self.dist_units.setText(_translate("MainWindow", "miles", None))
        self.speed_unit.setText(_translate("MainWindow", "mph", None))
        self.fuel_level_units.setText(_translate("MainWindow", "gallons", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

